## wordpress depolyment ##

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
      app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest                #wordpress:6.1.1
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        envFrom:
        - secretRef:
            name: wordpress-secrets
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-pv-claim   
