## Deploy Certificate Issuer ##
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <your-email-id> # ❗ Replace this with your email address
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: nginx