## Create Static IP for Load Balancer ##
#gcloud compute addresses create wordpress-ip --region asia-south1

---
## wordpress service ##			
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: "YOUR.IP.ADDRESS.HERE"  ## Regional Static IP